version: "3"
services: 
    pinart-multimedia-ms:
        container_name: docker-multimedia
        build:
            context: .
            dockerfile: PinArt-Multimedia-MS/Dockerfile
        ports: 
            - '3000:3000'
        links:
            - mongo
    pinart-feed-ms:
        container_name: docker-feed
        build:
            context: .
            dockerfile: PintArt-Feed-MS/Dockerfile
        ports: 
            - '3001:3001'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'